### ISSUE TITLE
run the template generator as a webhook/action

### ISSUE THREAD

**Issue by durandom** [open-services-group/community#26]
Can we run https://github.com/open-services-group/community/blob/main/Containerfile after something is merged?

**Comment by goern** [comment]
I'd say, the contributor should run it and add the result as the last commit of the PR?!

**Comment by tumido** [comment]
I've tried to convert it to a pre-commit hook via:

```yaml
# .pre-commit-config.yaml
repos:
  ...
  - repo: local
    hooks:
      - id: generator
        name: Generate content from sigs.yaml
        language: docker_image
        entry: quay.io/open-services-group/community-tooling:v0.1.0-dev
```

But it fails with:

```
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Validating sigs.yaml
2022/01/21 13:32:04 open sigs.yaml: permission denied
```

There is a bug with rootless container runtime in pre-commit

Relevant upstream issue and PR:
https://github.com/pre-commit/pre-commit/issues/1243
https://github.com/pre-commit/pre-commit/pull/1484

I'll try to make it work as a golang pre-commit plugin, though it may require to have the source code locally. I'll comment with a POC shortly.
